== Getting Started

In order to get started quickly with perfLoad and to demonstrate how everything works together, a demo setup is available that installs a complete perfLoad environment including all components together with a reference application on your local machine.

It includes a sample load test driver and several sample testplans which you may run and study in order to get familiar with perfLoad.

[discrete]
=== Installation

* Make sure `JAVA_HOME` is set to Java 8 (JDK or JRE).
* Download (link will follow once published) the demo installer and unzip it to some directory of your choice. You will find there a directory named `demo-installer`.
* Open a command prompt in this directory and run `DemoInstaller.cmd` or `./DemoInstaller`, depending on your operating system. The installer will then download and configure all components. You will be prompted for the demo installation directory. You may accept the default or enter a directory of you choice.

[source,bash]
----
demo-installer> DemoInstaller.cmd
Initializing...

        *******************************************************************
        *                                                                 *
        *                                                                 *
        *           Welcome to perfLoad's Demo Installer 1.0.0            *
        *             (c) 2013, mgm technology partners GmbH              *
        *                                                                 *
        *                                                                 *
        *******************************************************************

 > Enter installation directory [../perfload-demo]:
----

[discrete]
=== Running Sample Load Tests

* Open a command prompt in the directory `supervisor` in the directory where the demo was installed.
* Execute `runLoadTest.cmd` or `./runLoadTest`.
* You will be prompted for a testplan to run:

[source,bash]
----
perfload-demo\supervisor> runLoadTest.cmd
Initializing...

        *******************************************************************
        *                                                                 *
        *                                                                 *
        *             Welcome to perfLoad's Supervisor 2.0.1              *
        *             (c) 2013, mgm technology partners GmbH              *
        *                                                                 *
        *                                                                 *
        *******************************************************************

No tentant specified. Running in single-tenancy mode.

Please select the testplan you'd like to use:
  1) testplan_browse_error.xml
  2) testplan_browse_garbage.xml
  3) testplan_CPUload.xml
  4) testplan_garbage.xml
  5) testplan_long.xml
  6) testplan_persistent_garbage.xml
  7) testplan_short.xml
----

* You may execute any of these testplans. For a start, we'd recommand to select `testplan_short`. It runs about ten minutes.

That's it! Supervisor takes care of everything including startup and shutdown of the reference application.

[discrete]
=== Examining the Test Results

After successfully completing the test, perfAlyzer is launched creating a report, which is stored under `perfalyzer\output\<testplan>\<timestamp>\05_report\report.html`.
